### ISSUE TITLE
classic_1 module cannot be executed

### ISSUE THREAD

**Issue by xiaohanhan-626** [SAV-Open-Playground/savop#2]
What are the differences between different topology modules during protocol runtime? Another question is, when running the classic_1 module, the required_apps key in the SavAgent_config.py file in the container only has "bird", which causes the _config_validation function in sav_agent.py to return a ValueError("key missing in config"). How can this be resolved?

**Comment by Yuqian-Shi** [comment]
Thanks for letting us know these issues. For the first one, I'm not sure that you mean by protocol runtime, perhaps is related to BIRD configuration? For the second issue, the config files for `classic_1` is actually out of date, we are actively working on `conf_classic_2_Strict_uRPF_2N`, which you may use as reference. We will fix `classic_1` in coming commits.

**Comment by xiaohanhan-626** [comment]
Thank you for your answer, it is very important to me. I will continue to try to run conf_classic_2_Strict_uRPF_2N.
