### ISSUE TITLE
network_test/build_sender_and_receiver.sh cannot be executed

### ISSUE THREAD

**Issue by xiaohanhan-626** [SAV-Open-Playground/savop#4]
When running network_test/build_sender_and_receiver.sh, an error occurs indicating that the Dockerfile_Test file does not exist. How can this be resolved?

**Comment by MichaelYoungGo** [comment]
hi, there.  We have abandoned using shell scripts to generate network traffic，encourage you to use our lastest way and the related files of the old method will be deleted soon.  After the container starts running， there are two files,  UDP_client.py  and UDP_server.py in each docker container's /root/savop/extend_server/trafficTools directory.   To test SAV effectiveness, please use the two python scripts.   the UDP_server.py has two parameters，--dst and --trans_num，which respectively represents the IP for listenging and the numer of IP packets for reveiving.   the UDP_client.py has four parameters, --dst, --src, --iface, --trans_num，which respectively represents destination, source address, physical interface and the numer of IP packets for transmitting. thx for your question

**Comment by xiaohanhan-626** [comment]
Thank you very much for your reply. We will try the new method you provided and it will be very helpful for our subsequent larger scale testing.
