### ISSUE TITLE
the information in the sav_table 

### ISSUE THREAD

**Issue by xiaohanhan-626** [SAV-Open-Playground/savop#5]
After successfully running the image, each container has three parts in its sav_table: config, active_app, and local_fib. What information does each part contain?

**Comment by xiaohanhan-626** [comment]
Thanks for your response. I have another question: Is there a detailed output for the valid prefix information obtained after running the SAVNET protocol?

**Comment by Yuqian-Shi** [comment]
At this stage, I suggest you check the `server.log` under `logs` folder of each container, and looking for key word `ADDED`, that is where each SAV rule generated (which prefix is allowed at which interfaces)

**Comment by xiaohanhan-626** [comment]
Okay, I will pay attention to the more detailed information in the server.log . Thank you very much for your help.
